### ISSUE TITLE
Since this can do network calls you should handle it on another thread.

### ISSUE THREAD

**Issue by doncung** [cake7914/Locavore#44]
https://github.com/cake7914/Locavore/blob/bc584994bb3d891a338162afbe8175e1bfd82f41/app/src/main/java/com/example/locavore/Fragments/FeedFragment.java#L108

Since getFarms can call queryFarms under the hoods and does it synchronously theoretically there is the danger here of this always failing due to making a network call on ui thread (I assume onLocationChanged is called from ui thread, but let me know if Google is doing something different). I know in practice it is unlikely since you have done prefetching in splash screen, but you do have conditions that may cause this to update like changing radius so it's better to handle appropriately.

**Comment by cake7914** [comment]
Removed this call as it was unnecessary.
