### ISSUE TITLE
You can use this class to help with list management

### ISSUE THREAD

**Issue by doncung** [cake7914/Locavore#45]
https://github.com/cake7914/Locavore/blob/bc584994bb3d891a338162afbe8175e1bfd82f41/app/src/main/java/com/example/locavore/Fragments/FeedFragment.java#L126

This is the class I was referring to when I was telling you about how Android can help manage the differences between lists.
https://developer.android.com/reference/androidx/recyclerview/widget/DiffUtil
You are free to do things manually as well, but this will make things easier for more complicated changes.

**Comment by cake7914** [comment]
Implemented DiffUtil class for profilesAdapters and EventsAdapter updates.
